[appendix]
== ビットコインホワイトペーパーの正誤表

この付録には、サトシ・ナカモトの論文「Bitcoin: A Peer-to-Peer Electronic Cash System」における既知の問題の説明、および用語の変更と、論文で説明されている内容とビットコインの実装がどのように異なるかについての注釈が含まれています。

この文書は、2016年に本書の共著者によって最初に公開されました。ここでは更新された形で再現しています。この正誤表の各セクションの名前は、ナカモトのオリジナルの論文のセクション名に対応しています。

=== 要約

____
「最長のチェーンは、目撃されたイベントの順序の証明としてだけでなく、最大の CPU パワーのプールから来たことの証明としても機能します。」
____

* *実装の詳細:* チェーン内の各リンク（ビットコインでは「ブロック」と呼ばれる）が同じ量の _プルーフ・オブ・ワーク_ (PoW) を使用して構築された場合、最長のチェーンは最大の計算能力のプールによって支えられたものになります。しかし、ビットコインはブロック間で PoW の量が変動するように実装されたため、「最長のチェーン」ではなく「最も PoW を示すチェーン」を確認することが重要になりました。これはしばしば「最も作業をしたチェーン」と略されます。
+
https://oreil.ly/XYZzx[変更]
は、最長のチェーンを確認することから最も作業をしたチェーンを確認することへの変更が、ビットコインの初期リリースからかなり後の2010年7月に行われました：
+
[source,diff]
----
-    if (pindexNew->nHeight > nBestHeight)
+    if (pindexNew->bnChainWork > bnBestChainWork)
----

[role="less_space pagebreak-before"]
* *用語の変更:* 初期のビットコインブロックの PoW 生成には一般的な CPU が使用されていましたが、今日では PoW 生成は主に専門のアプリケーション固有集積回路 (ASIC) によって行われています。そのため、「CPU パワー」と言うよりも、「計算能力」または単に PoW 生成に使用されるハッシュレートと言う方がより正確かもしれません。

____
「ネットワークを攻撃するために協力していないノードによって CPU パワーの過半数が制御されている限り、彼らは最長のチェーンを生成し、攻撃者を追い越します。」
____


* *用語の変更:* 現在、「ノード」という用語は、システムのすべてのルールを強制するプログラムである完全な検証ノードを指すために使用されています。今日、チェーンを拡張するプログラム（およびハードウェア）は、論文の第 6 節で中本が金鉱掘りに例えたことから「マイナー」と呼ばれています。中本はすべてのマイナーがノードであることを期待していましたが、彼がリリースしたソフトウェアはすべてのノードがマイナーであることを要求していませんでした。元のソフトウェアでは、ノードの GUI にあるシンプルなメニュー項目でマイニング機能をオンまたはオフに切り替えることができました。
+
今日では、圧倒的多数のノードがマイナーではなく、マイニングハードウェアを所有する多くの個人がそれを自分のノードで使用していません（そして、自分のノードでマイニングを行う人々でさえ、新しく発見されたブロックの上で短期間だけマイニングを行い、そのノードが新しいブロックを有効と見なすことを確認しないことがよくあります）。論文の初期の部分では、「ノード」が主に修飾なしで使用されており、完全な検証ノードを使用したマイニングを指しています。論文の後半部分で「ネットワークノード」と言及されているのは、ノードがマイニングを行っていなくてもできることについて主に述べています。
* *公開後の発見:* 新しいブロックが生成されると、そのブロックを生成したマイナーはすぐにその続編に取り組むことができますが、他のすべてのマイナーは新しいブロックを知らず、それがネットワークを通じて伝播するまで取り組むことができません。これにより、多くのブロックを生成するマイナーは、少ないブロックを生成するマイナーに対して優位性を持ち、_セルフィッシュマイニング攻撃_ として知られる方法で、ネットワーク全体のハッシュレートの約 30% を持つ攻撃者が他のマイナーをより利益が少なくなるようにし、攻撃するマイナーの方針に従わせる可能性があります。したがって、「ネットワークを攻撃するために協力していないノードが CPU パワーの過半数を制御している」と言う代わりに、「ネットワークを攻撃するために協力しているノードがネットワークの約 30% 未満を制御している限り」と言う方が正しいかもしれません。

=== トランザクション

____
「電子コインをデジタル署名のチェーンとして定義します。各所有者は、前のトランザクションのハッシュと次の所有者の公開鍵をデジタル署名し、これらをコインの末尾に追加することでコインを次に転送します。」
____

* *実装の詳細:* Bitcoin はこのシステムのより一般的なバージョンを実装しており、デジタル署名を直接使用するのではなく、「決定論的な式」を使用します。既知の公開鍵に一致する署名が支払いを可能にするのと同様に、既知の式を満たすデータも支払いを可能にします。一般的に、Bitcoin でコインを使うために満たさなければならない式は「負担」として知られています。これまでのところ、Bitcoin のほとんどすべての負担は少なくとも 1 つの署名を提供することを要求しています。したがって、「デジタル署名のチェーン」と言う代わりに、「負担のチェーン」と言う方が正確です。トランザクションにはしばしば複数の入力と複数の出力があるため、その構造はあまりチェーンのようではなく、有向非巡回グラフ (DAG) としてより正確に説明されます。

=== Proof of Work

____
"...我々はブロック内のナンスをインクリメントすることによってプルーフ・オブ・ワークを実装し、ブロックのハッシュに必要なゼロビットを与える値が見つかるまで続けます。"
____

* *実装の詳細:* Adam Back の Hashcash 実装は、必要な数の先頭ゼロビットを持つハッシュを見つけることを要求します。Bitcoin はハッシュを整数として扱い、それが指定された整数よりも小さいことを要求します。これにより、実質的にビット数を小数で指定することが可能になります。

____
"プルーフ・オブ・ワークは本質的に 1 CPU 1 票です。"
____

* *重要な注意:* ここでの投票はシステムのルールに対するものではなく、単にトランザクションの順序を決定するためのものであり、「電子コイン」が簡単に二重支払いされないように保証を提供するためのものです。これは論文の第 11 節でより詳細に説明されています。そこでは、「攻撃者が正直なチェーンよりも速く代替チェーンを生成しようとするシナリオを考えます。たとえこれが達成されたとしても、システムが任意の変更に開かれることはなく、例えば無から価値を創造したり、攻撃者に属していなかったお金を取ったりすることはできません。ノードは無効なトランザクションを支払いとして受け入れることはなく、正直なノードはそれを含むブロックを決して受け入れません。」と述べられています。

____
"...proof-of-work difficulty is determined by a moving average targeting an
average number of blocks per hour."
____

* *実装の詳細:* 移動平均は使用されていません。代わりに、2,016 番目のブロックの生成時間が以前のブロックの生成時間と比較され、その差を使用して調整に使用される平均が計算されます。
+
さらに、Bitcoin で実装されている平均は、テキストが示唆するような 1 時間あたりの平均ブロック数ではなく、2 週間あたりの平均ブロック数をターゲットにしています。他の実装されたルールは、調整をさらに遅くする可能性があります。たとえば、調整が期間ごとにブロック生成速度を 300% 以上増加させることも、75% 以上減少させることもできないというルールです。

=== Reclaiming Disk Space

____
"Once the latest transaction in a coin is buried under enough blocks, the
spent transactions before it can be discarded to save disk space."
____

* *公開後の発見の可能性:* このセクションで説明されているメルクルツリー構造は、特定のブロックにトランザクションが含まれていたことを証明できますが、トランザクションが未使用であることを証明する方法は現在のところ Bitcoin にはありません。これは、すべての新しいノードがすべてのトランザクションを処理する必要があるため、ここで説明されている方法がすべてのノード間でディスクスペースを回収するために普遍的に使用できないことを意味します。

=== Simplified Payment Verification

____
"One strategy to protect against this would be to accept alerts from
network nodes when they detect an invalid block, prompting the user’s
software to download the full block and alerted transactions to confirm
the inconsistency."
____

* *重要な注意:* このセクションの一部を実装し、簡易支払い検証 (SPV) と呼ばれるソフトウェアが作成されていますが、これらのプログラムのいずれも、無効なブロックが検出されたときにネットワークノード (完全検証ノード) からのアラートを受け入れていません。これにより、過去にいわゆる SPV ウォレットにビットコインがリスクにさらされました。


=== プライバシー

____
「複数入力のトランザクションでは、入力が同じ所有者によって所有されていることが必然的に明らかになるため、いくつかのリンク（プライバシー、ビットコインホワイトペーパーの誤り）は依然として避けられません。」
____

* *公開後の発明:* 所有者がしばしば他の所有者の入力と自分の入力を混ぜる場合、同じトランザクション内の異なる入力が同じ所有者であることは明らかではありません。例えば、アリスとボブがそれぞれの入力を1つずつ提供してチャーリーとダンに支払う場合と、アリスが2つの入力を提供してチャーリーとダンに支払う場合の間に公的な違いはありません。
+
この技術は今日では https://oreil.ly/UBEJX[CoinJoin] として知られており、それを実装するソフトウェアは2015年から使用されています。

=== 計算

____
「受信者（計算、ビットコインホワイトペーパーの誤り）は、新しい鍵ペアを生成し、署名の直前に公開鍵を送信者に渡します。これにより、送信者が事前にブロックチェーンを準備し、運が良ければ十分に先に進むまで継続的に作業し、その瞬間にトランザクションを実行することを防ぎます。」
____

* *公開後の発見:* 受信者が支出者がトランザクションに署名する直前に公開鍵を生成することは、支出者が事前にブロックチェーンを準備することを防ぎません。初期のビットコインユーザである Hal Finney はこの攻撃を発見し、https://oreil.ly/kg_Xe[説明しました]：「攻撃者が時折ブロックを生成していると仮定します。彼が生成する各ブロックには、彼が制御するアドレス A からアドレス B への転送が含まれています。
+
「あなたを騙すために、彼がブロックを生成すると、それを放送しません。代わりに、彼はあなたの店に駆け込み、アドレス A からあなたのアドレス C に支払いを行います。あなたは数秒待ち、何も聞こえないので商品を渡します。彼は今ブロックを放送し、彼のトランザクションがあなたのものより優先されます。」
+
この攻撃は任意の数の確認に対して機能し、時には Finney Attack と呼ばれます。

'''''

*免責事項:* この文書の著者は、ここで説明されている問題のいずれも最初に特定したわけではなく、単にそれらを1つの文書にまとめただけです。


*ライセンス:* この正誤表ドキュメントは https://oreil.ly/xZeBR[CC0] 1.0 Universal Public Domain Dedication の下で公開されています。

この本の出版後に行われた更新については、https://oreil.ly/ygExa[オリジナル ドキュメント] をご覧ください。
