[preface]
== 序文

=== ビットコインの本を書く

私 (アンドレアス) が初めてビットコインに出会ったのは 2011 年の中頃でした。最初の反応は「ふん！オタクのお金か！」というもので、重要性を理解できずにさらに 6 か月間無視していました。この反応は、私が知っている最も賢い人々の多くにも見られるもので、少し安心感を覚えます。2 度目にビットコインに出会ったのは、メーリングリストの議論の中でした。そのとき、サトシ・ナカモトが書いたホワイトペーパーを読んで、何が書かれているのかを理解しようと決めました。あの 9 ページを読み終えた瞬間を今でも覚えています。ビットコインが単なるデジタル通貨ではなく、通貨以上の基盤を提供できる信頼のネットワークであることに気づいたのです。「これはお金ではなく、分散型の信頼ネットワークだ」という認識が、私をビットコインに関するあらゆる情報を貪り尽くす 4 か月の旅へと駆り立てました。私は夢中になり、1 日 12 時間以上も画面に釘付けになりながら、読み、書き、コーディングし、できる限り多くのことを学びました。この状態から抜け出したときには、食事が不規則だったために体重が 20 ポンド以上減っていましたが、ビットコインに取り組むことに専念する決意を固めていました。

それから 2 年後、ビットコイン関連のサービスや製品を探求するためにいくつかの小さなスタートアップを立ち上げた後、最初の本を書く時が来たと決めました。ビットコインは私を創造性の狂乱に駆り立て、私の思考を支配したテーマであり、インターネット以来最もエキサイティングな技術でした。この素晴らしい技術に対する私の情熱を、より広いオーディエンスと共有する時が来たのです。

=== 想定読者

この本は主にコーダーを対象としています。プログラミング言語を使えるなら、この本は暗号通貨がどのように機能するか、どのように使用するか、そしてそれに関連するソフトウェアをどのように開発するかを教えます。最初の数章は、ビットコインや暗号通貨の内部構造を理解しようとしている非コーダーにとっても、詳細な入門書として適しています。

=== なぜカバーにバグがいるのか？

ハキリアリは、コロニー超個体において非常に複雑な行動を示す種ですが、個々のアリは社会的な相互作用と化学的な香り（フェロモン）の交換によって駆動される一連の単純なルールに従って動きます。Wikipedia によると、「人間に次いで、ハキリアリは地球上で最大かつ最も複雑な動物社会を形成します。」ハキリアリは実際には葉を食べるのではなく、それを使って菌類を栽培し、コロニーの中心的な食料源としています。わかりますか？これらのアリは農業をしているのです！

アリは階級に基づく社会を形成し、子孫を産むための女王がいますが、アリのコロニーには中央の権威やリーダーは存在しません。数百万のメンバーからなるコロニーが示す高度で洗練された行動は、社会的ネットワークにおける個々の相互作用から生じる創発的な特性です。

自然は、分散型システムが中央の権威、階層、または複雑な部品を必要とせずに、回復力を持ち、創発的な複雑さと驚くべき洗練を生み出すことができることを示しています。

ビットコインは、無数の金融プロセスをサポートできる非常に洗練された分散型信頼ネットワークです。しかし、ビットコインネットワーク内の各ノードは、いくつかの単純なルールに従います。多くのノード間の相互作用が、洗練された行動の創発につながるのであり、単一のノードにおける固有の複雑さや信頼ではありません。アリのコロニーのように、ビットコインネットワークは、単純なルールに従う単純なノードの回復力のあるネットワークであり、中央の調整なしに驚くべきことを成し遂げることができます。

=== 本書で使用される表記法

本書では、以下の表記法を使用します：

_イタリック_:: 新しい用語、URL、メールアドレス、ファイル名、ファイル拡張子を示します。

+等幅+:: プログラムリスト、および変数名や関数名、データベース、データ型、環境変数、ステートメント、キーワードなどのプログラム要素を段落内で参照するために使用します。

**`等幅太字`**:: ユーザが文字通り入力する必要があるコマンドやその他のテキストを示します。

_++等幅イタリック++_:: ユーザが提供する値や文脈によって決定される値に置き換えるべきテキストを示します。

[TIP]
====
この要素はヒントや提案を示します。
====

[NOTE]
====
この要素は一般的な注意事項を示します。
====

[WARNING]
====
この要素は警告や注意を示します。
====

=== コード例

すべてのコードスニペットは、対応する言語のコンパイラやインタプリタを最小限インストールすることで、ほとんどのオペレーティングシステムで再現できます。必要に応じて、基本的なインストール手順とそれらの手順の出力例をステップバイステップで提供します。

一部のコードスニペットとコード出力は印刷用に再フォーマットされています。そのような場合、行はバックスラッシュ (\\) 文字と改行文字で分割されています。例を転記する際には、これらの2文字を削除して行を再結合すると、例に示されているのと同じ結果が得られるはずです。

すべてのコードスニペットは、可能な限り実際の値と計算を使用しているため、例から例へと構築し、同じ値を計算するために書いたコードでも同じ結果を見ることができます。

=== コード例の使用

この本は、あなたの仕事を手助けするためにあります。一般的に、この本に例として提供されているコードは、あなたのプログラムやドキュメントで使用してかまいません。コードの大部分を再現するのでない限り、許可を求める必要はありません。たとえば、この本からいくつかのコードチャンクを使用するプログラムを書く場合、許可は必要ありません。O'Reilly の本からの例を販売または配布する場合は許可が必要です。この本を引用して例のコードを引用することで質問に答える場合、許可は必要ありません。この本の例のコードを大量に製品のドキュメントに組み込む場合は許可が必要です。

帰属表示は感謝しますが、必須ではありません。帰属表示には通常、[.keep-together]#タイトル、# 著者、出版社、ISBN が含まれます。例：「_Mastering Bitcoin_, 3rd ed., by [.keep-together]#Andreas M.# Antonopoulos and David A. Harding (O’Reilly). Copyright 2024 David Harding, ISBN 978-1-098-15009-9.」

この本の一部の版は、https://oreil.ly/RzUHE[CC-BY-NC] などのオープンソースライセンスの下で提供されており、その場合はそのライセンスの条件が適用されます。


コード例の使用がフェアユースや上記の許可を超えていると感じた場合は、pass:[<a href="mailto:permissions@oreilly.com">permissions@oreilly.com</a>] までお気軽にお問い合わせください。

=== 前版からの変更点

include::meta/third_edition_changes.asciidoc[]

=== 本書におけるビットコインアドレスとトランザクション

本書で使用されているビットコインアドレス、トランザクション、鍵、QRコード、およびブロックチェーンデータは、ほとんどが実際のものです。つまり、ブロックチェーンを閲覧したり、例として示されたトランザクションを見たり、自分のスクリプトやプログラムでそれらを取得したりすることができます。

ただし、アドレスを構築するために使用された秘密鍵は、本書に印刷されているか「焼かれている」ことに注意してください。つまり、これらのアドレスにお金を送ると、そのお金は永遠に失われるか、場合によっては本書を読めるすべての人が印刷された秘密鍵を使ってそれを取ることができます。

[WARNING]
====
本書のアドレスにお金を送らないでください。他の読者に取られるか、永遠に失われます。
====

=== オライリーオンラインラーニング
[role = "ormenabled"]
[NOTE]
====
40年以上にわたり、pass:[<a href="https://oreilly.com" class="orm:hideurl"><em class="hyperlink">オライリー・メディア</em></a>] は、企業の成功を支援するために技術とビジネスのトレーニング、知識、洞察を提供してきました。
====

私たちのユニークな専門家とイノベーターのネットワークは、本、記事、オンラインラーニングプラットフォームを通じて知識と専門知識を共有しています。オライリーのオンラインラーニングプラットフォームは、ライブトレーニングコース、詳細な学習パス、インタラクティブなコーディング環境、オライリーおよび200以上の他の出版社からの膨大なテキストとビデオコレクションへのオンデマンドアクセスを提供します。詳細については、pass:[<a href="https://oreilly.com" class="orm:hideurl"><em>https://oreilly.com</em></a>] をご覧ください。

=== お問い合わせ方法

本書に関するコメントや質問は、出版社までお寄せください。

++++
<ul class="simplelist">
  <li>オライリー・メディア株式会社</li>
  <li>1005 Gravenstein Highway North</li>
  <li>Sebastopol, CA 95472</li>
  <li>800-889-8969 (アメリカまたはカナダ)</li>
  <li>707-829-7019 (国際またはローカル)</li>
  <li>707-829-0104 (ファックス)</li>
  <li><a class="email" href="mailto:support@oreilly.com"><em>support@oreilly.com</em></a></li>
  <li><a href="https://www.oreilly.com/about/contact.html"><em>https://www.oreilly.com/about/contact.html</em></a></li>
</ul>
++++

私たちはこの本のためのウェブページを持っており、そこには正誤表、例、および追加情報を掲載しています。このページには次のリンクからアクセスできます：link:$$https://oreil.ly/MasteringBitcoin3e$$[]。

++++
<!--上記のリンクを忘れずに更新してください。-->
++++

私たちの本やコースに関するニュースや情報については、次のリンクをご覧ください：link:$$https://oreilly.com$$[]。

LinkedIn で私たちを見つけてください：link:$$https://linkedin.com/company/oreilly-media$$[]。

Twitter で私たちをフォローしてください：link:$$https://twitter.com/oreillymedia$$[]。

YouTube で私たちを見てください：link:$$https://youtube.com/oreillymedia$$[]。


=== 著者への連絡

++++
<p class="left-align">
Andreas M. Antonopoulos に連絡するには、彼の個人サイトをご覧ください：
<span class="keep-together"><a href="https://antonopoulos.com"><em class="hyperlink">https://antonopoulos.com</em></a>。</span></p>
++++

Facebook で Andreas をフォローしてください：
link:$$https://facebook.com/AndreasMAntonopoulos$$[]。

Twitter で Andreas をフォローしてください：
link:$$https://twitter.com/aantonop$$[]。

LinkedIn で Andreas をフォローしてください：
link:$$https://linkedin.com/company/aantonop$$[]。

毎月の寄付を通じて Andreas の仕事を支援しているすべてのパトロンに感謝します。彼の Patreon ページはこちらです：
link:$$https://patreon.com/aantonop$$[]。

_Mastering Bitcoin_ に関する情報、および Andreas のオープンエディションと翻訳については、次のリンクをご覧ください：
link:$$https://bitcoinbook.info$$[]。

David A. Harding に連絡するには、彼の個人サイトをご覧ください：
link:$$https://dtrt.org$$[]。

=== 第一版および第二版への謝辞

_By Andreas M. Antonopoulos_

この本は多くの人々の努力と貢献の結晶です。友人、同僚、そして完全な見知らぬ人々から受けたすべての助けに感謝しています。彼らは私と共に、暗号通貨とビットコインに関する決定版の技術書を書くというこの努力に参加してくれました。

ビットコイン技術とビットコインコミュニティを区別することは不可能であり、この本はそのコミュニティの産物であると同時に技術に関する本でもあります。この本の執筆において、ビットコインコミュニティ全体からの励まし、応援、支援、そして報酬を受けました。何よりも、この本は私が素晴らしいコミュニティの一員となることを可能にしてくれました。私をこのコミュニティに受け入れてくれたことに感謝します。名前を挙げるにはあまりにも多くの人々がいます。会議、イベント、セミナー、ミートアップ、ピザ集会、小さなプライベート集会で出会った人々、そして Twitter、reddit、bitcointalk.org、GitHub で私とコミュニケーションを取った多くの人々がこの本に影響を与えました。この本にあるすべてのアイデア、アナロジー、質問、回答、説明は、コミュニティとのやり取りを通じてインスピレーションを受け、テストされ、改善されました。皆さんのサポートに感謝します。皆さんがいなければこの本は実現しませんでした。心から感謝しています。

著者になる旅は、もちろん最初の本を書くずっと前から始まります。私の第一言語（および学業）はギリシャ語だったため、大学の1年目に英語の補習作文コースを受ける必要がありました。その年に自信とスキルを築く手助けをしてくれた英語作文の先生、ダイアナ・コーダスに感謝しています。後にプロとして、データセンターに関する技術的な執筆スキルを磨き、_Network World_ 誌に寄稿しました。_Network World_ でコラムニストとして初めての執筆の仕事を与えてくれたジョン・ディックスとジョン・ガラント、そして私のコラムを編集し、出版に適した形にしてくれた編集者のマイケル・クーニーと同僚のジョナ・ティル・ジョンソンに感謝しています。4年間、毎週500語を書くことで、最終的に著者になることを考えるのに十分な経験を積むことができました。

O'Reilly に書籍提案を提出した際に、推薦状を提供し、提案をレビューしてくれた方々にも感謝しています。特に、ジョン・ガラント、グレゴリー・ネス、リチャード・スティーノン、ジョエル・スナイダー、アダム・B・レヴィン、サンドラ・ギトレン、ジョン・ディックス、ジョナ・ティル・ジョンソン、ロジャー・ヴァー、ジョン・マトニスに感謝しています。特に、提案の初期バージョンをレビューしてくれたリチャード・ケイガンとティモン・マトスコ、そして提案を校正してくれたマシュー・テイラーに感謝しています。

O'Reilly のタイトル _DNS and BIND_ の著者であるクリケット・リューに、O'Reilly を紹介してくれたことに感謝しています。また、数か月にわたりこの本の実現を手助けしてくれた O'Reilly のマイケル・ルキデスとアリソン・マクドナルドにも感謝しています。特にアリソンは、予定していたスケジュールに生活が介入し、締め切りが守れず納品が遅れたときにも忍耐強く対応してくれました。第2版では、プロセスを導いてくれたティモシー・マクガバン、忍耐強く編集してくれたキム・コーファー、多くの新しい図を描いてくれたレベッカ・パンザーに感謝しています。

最初の数章の最初の数稿は最も難しかったです。なぜなら、ビットコインは解きほぐすのが難しいテーマだからです。ビットコイン技術の一つの糸を引っ張るたびに、全体を引っ張らなければなりませんでした。テーマを理解しやすくし、密度の高い技術的なテーマに物語を作り上げるのに苦労し、何度も行き詰まり、少し落胆しました。最終的に、ビットコインを使用する人々の物語を通じてビットコインの物語を語ることに決め、全体の本を書くのがずっと楽になりました。物語を解きほぐし、ライターズブロックの瞬間を乗り越える手助けをしてくれた友人でありメンターであるリチャード・ケイガンに感謝しています。第1版と第2版の各章の初期稿をレビューし、より良くするために難しい質問をしてくれたパメラ・モーガンにも感謝しています。また、サンフランシスコ・ビットコイン・デベロッパーズ・ミートアップグループの開発者たち、そして初期の資料をテストするのを手伝ってくれたターリク・ルイスとデニス・テリーにも感謝しています。インフォグラフィックデザインを担当してくれたアンドリュー・ノーグラーにも感謝しています。

本書の開発中、私は初期の草稿を GitHub で公開し、一般からのコメントを募りました。その結果、100 を超えるコメント、提案、修正、貢献が寄せられました。これらの貢献は、<<github_contrib>> で明確に謝辞を述べています。特に、ボランティアの GitHub 編集者である Ming T. Nguyen さん（第 1 版）と Will Binns さん（第 2 版）には、GitHub 上でプルリクエストや問題報告の管理、バグ修正を精力的に行っていただき、心から感謝しています。

本書が草稿として完成した後、何度かの技術レビューを経ました。Cricket Liu さんと Lorne Lantz さんには、徹底したレビュー、コメント、サポートをいただき、感謝しています。

いくつかの Bitcoin 開発者がコードサンプル、レビュー、コメント、励ましを提供してくれました。Amir Taaki さんと Eric Voskuil さんには、コードスニペットと多くの素晴らしいコメントを、Chris Kleeschulte さんには Bitcore に関する情報を、Vitalik Buterin さんと Richard Kiss さんには楕円曲線数学とコードの貢献を、Gavin Andresen さんには修正、コメント、励ましを、Michalis Kargakis さんにはコメント、貢献、btcd の執筆を、Robin Inge さんには第 2 版を改善するための正誤表の提出をいただきました。第 2 版では、再び多くの Bitcoin Core 開発者から多大な支援を受けました。特に、Eric Lombrozo さんには Segregated Witness の解説を、Luke Dashjr さんにはトランザクションに関する章の改善を、Johnson Lau さんには Segregated Witness やその他の章のレビューをしていただきました。他にも多くの方々に感謝しています。Joseph Poon さん、Tadge Dryja さん、Olaoluwa Osuntokun さんには、Lightning Network の説明、執筆のレビュー、質問への回答をしていただき、感謝しています。

私が言葉と本を愛するようになったのは、母 Theresa のおかげです。彼女は家の壁という壁に本を並べて育ててくれました。母は自称テクノフォビアでありながら、1982 年に私に初めてのコンピュータを買ってくれました。父 Menelaos は土木技師で、80 歳で初めての本を出版したばかりですが、論理的かつ分析的な思考、そして科学と工学への愛を教えてくれました。

皆様、この旅を通じて私を支えてくださり、ありがとうございます。

=== 第三版への謝辞

_デイビッド・A・ハーディング_

<<schnorr_signatures>> で最初にインタラクティブなシュノア識別プロトコルを説明することから始まる、非インタラクティブなシュノア署名プロトコルの紹介は、グレゴリー・マクスウェルとアンドリュー・ポエルストラによる「Borrommean Ring Signatures」(2015) の紹介に大きく影響を受けています。この 10 年間にわたり、彼らから多くの無償の支援を受けたことに深く感謝しています。

この原稿の草稿に対して、ホルヘ・レスメス、オラオルワ・オスントクン、レネ・ピックハルト、そしてマーク「マーチ」エアハルトが非常に貴重な技術的レビューを提供してくださいました。特に、マーチの非常に詳細で洞察に満ちたレビューと、同じテキストの複数のバージョンを評価する意欲が、この本の質を私の最高の期待を超えるものにしてくれました。

また、このプロジェクトに私を推薦してくれたジミー・ソング、ベストセラーのテキストを更新することを許可してくれた共著者のアンドレアス、オライリーの著作プロセスを案内してくれたアンジェラ・ルフィーノ、そして第三版の執筆を楽しく生産的な経験にしてくれたオライリーの他のスタッフの皆様にも感謝の意を表します。

最後に、私の旅を助けてくれたすべてのビットコインの貢献者にどのように感謝すればよいかわかりません。私が使用するソフトウェアを作成し、それがどのように機能するかを教えてくれ、私が得たわずかな知識を伝えるのを助けてくれた皆様です。名前を挙げるには多すぎますが、皆様のことをよく思い出し、私のこの本への貢献が皆様の支えなしには不可能だったことを知っています。

[[github_contrib]]
=== 早期リリース草稿 (GitHub 貢献)

多くの貢献者が GitHub 上の早期リリース草稿にコメント、修正、追加を提供してくださいました。この本への貢献に感謝します。

以下は、GitHub ID を含む注目すべき GitHub 貢献者のリストです：

include::meta/github_contrib.adoc[]
